{
  "id": "252c34ed-cdf3-4a16-ad6d-f29040098d05",
  "file_path": "./test-api-data/storage/documents/252c34ed-cdf3-4a16-ad6d-f29040098d05.md",
  "original_path": "repos/kota-db/files/clients/python/kotadb/exceptions.py",
  "title": "File: clients/python/kotadb/exceptions.py",
  "size": 770,
  "created": 1757262565,
  "updated": 1757262565,
  "hash": [
    138,
    98,
    219,
    134,
    28,
    254,
    190,
    73,
    110,
    107,
    39,
    164,
    235,
    60,
    138,
    97,
    184,
    113,
    128,
    27,
    247,
    215,
    213,
    248,
    107,
    128,
    203,
    79,
    225,
    53,
    220,
    245
  ],
  "embedding": null
}