{
  "id": "493c3406-0c72-41d4-b033-d368c7da9ee9",
  "file_path": "./kotadb-data/storage/documents/493c3406-0c72-41d4-b033-d368c7da9ee9.md",
  "original_path": "repos/kota-db/files/clients/python/kotadb/exceptions.py",
  "title": "File: clients/python/kotadb/exceptions.py",
  "size": 770,
  "created": 1757473562,
  "updated": 1757473562,
  "hash": [
    138,
    98,
    219,
    134,
    28,
    254,
    190,
    73,
    110,
    107,
    39,
    164,
    235,
    60,
    138,
    97,
    184,
    113,
    128,
    27,
    247,
    215,
    213,
    248,
    107,
    128,
    203,
    79,
    225,
    53,
    220,
    245
  ],
  "embedding": null
}